<?xml version="1.0"?>
<package format="3">
  <name>faster</name>
  <version>0.1.0</version>
  <description>Faster trajectory planner using JPS and Gurobi modified for ros2 use</description>
  <maintainer email="konstantin.stute@stud.tu-darmstadt.de">Konstantin Stute</maintainer>
  <license>BSD-3-Clause</license>

  <!-- Build tool -->
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>decomp_ros_utils</depend>
  <depend>decomp_ros_msgs</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>pcl_conversions</depend>
  <depend>tf2_sensor_msgs</depend>
  <depend>message_filters</depend>

  <!-- Build dependencies -->
  <build_depend>rclcpp</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>nav_msgs</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>visualization_msgs</build_depend>
  <build_depend>pcl_ros</build_depend>
  <build_depend>faster_msgs</build_depend>
  <build_depend>decomp_util</build_depend>
  <build_depend>jps3d</build_depend>

  <!-- Execution dependencies (same as build, minus ament_cmake) -->
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>pcl_ros</exec_depend>
  <exec_depend>faster_msgs</exec_depend>
  <exec_depend>decomp_util</exec_depend>
  <exec_depend>jps3d</exec_depend>

  <!-- Test dependencies (optional) -->
  <!-- <test_depend>ament_lint_auto</test_depend> -->

  <!-- Export section -->
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
